// Zebra bitmap font extracted from reference test images
// Real Zebra firmware output, pixel-perfect
export interface ZebraBitmapFont {
  height: number;
  chars: {[ch: string]: {w: number; a: number; b: string}};
}

export const ZEBRA_FONTS: {[moduleWidth: number]: ZebraBitmapFont} = {
  3: {
    height: 19,
    chars: {
      "*":{w:11,a:19,b:"BADAGAMAYczH4HALAzDCAAAAAAAAAAAAAAAA"},
      "1":{w:11,a:17,b:"DAeCEAIAQAgBACAEAIAQAgBACAEAIAQAg/+A"},
      "2":{w:12,a:18,b:"DwMMQGQCgCADACAGAEAIAQAgBACAEAIAQAgC//A="},
      "3":{w:12,a:15,b:"DwIMQCACACACACAMB4AMACADABABABADgCYMHwA="},
      "4":{w:11,a:18,b:"AcB4CwNgTBGCMIYQxBiDIGwN/8AwBgDAGB+A"},
      "5":{w:12,a:12,b:"f+YAYAYAYAYAYAb4IEACABABABABABADgCYMHwA="},
      "A":{w:18,a:20,b:"AAAH+AAaAASAARAAxAAhAAggBggBAgBAQDAQD/4CAIEAIEAMEAEIAE/A/A=="},
      "B":{w:14,a:18,b:"AAP/AgMIBCAIgCIAiAYgMP+CAYgDIASAEgBIASAMgG/+AA=="},
      "C":{w:14,a:19,b:"AAAfEYPIA2ANABwAIACAAgAIACAAgAMABAAIASAMYMA8AA=="},
    },
  },
  4: {
    height: 25,
    chars: {
      "*":{w:14,a:24,b:"AwAMADAAwAMCDB8zx/gHgB4AzAMwGGDAwgEAAAAAAAAAAAAAAAAAAAAAAAA="},
      "1":{w:15,a:22,b:"AQAeAcQECAAQACAAQACAAQACAAQACAAQACAAQACAAQACAAQACAAQACAAQH////4="},
      "2":{w:16,a:25,b:"A+AP+BwMOAYwA2ADYAEAAQADAAMABgAMABgAMABgAMABgAMABgAMABgAcAHAAf////8="},
      "3":{w:16,a:24,b:"A+AP+DgccAxgBgACAAIAAgAGAAQAHAP4A/AAGAAOAAIAAwADAAMAA4AD4AZ4HB/4B+A="},
      "4":{w:15,a:24,b:"AHgA8ANgDMAZgGMAxgMMBBgYMGBgwMMBhAMYBiAM/////ABgAMABgAMABgD/Af4="},
      "5":{w:16,a:16,b:"P/w//DAAMAAwADAAMAAwADAAM+A/+DAMAAYAAwADAAMAAwADAAMAA4AG4A54HB/4B+A="},
      "A":{w:23,a:25,b:"AAAAAAAAf+AA/8AABoAACYAAMQAAQwABhgADBAAEDAAYGAAgEABAMAGAIAIAYA//wB//gCABgMADAQACBgAGDAAEf4D//wH+"},
      "B":{w:20,a:25,b:"AAAAAAD//A//8BgDgYAYGADBgAwYAMGADBgBgYAwH/4B//AYAcGABhgAYYADGAAxgAMYADGABhgAz//4//4A"},
      "C":{w:19,a:26,b:"AAAAAAAHwQf+YcB8YAOYADMABsAAWAACAABAAAgAAQAAIAAEAACAABgAAwAAMAAzAAwwA4OB4D/wAfgA"},
    },
  },
  5: {
    height: 32,
    chars: {
      "*":{w:18,a:30,b:"AMAAMAAMAAMAAMAAMAAMAwMD8MfP98B/gAeAA+AAzABjgDBwHA4GAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
      "1":{w:18,a:28,b:"AEAA8AH8A+MAwMAAMAAMAAMAAMAAMAAMAAMAAMAAMAAMAAMAAMAAMAAMAAMAAMAAMAAMAAMAAMAAMAAMAAMAAMA//////AAA"},
      "2":{w:20,a:31,b:"APgAP/APA4HAHDgA4wAGYAAyAAMAADAAAwAAMAAGAABgAAwAAYAAMAAGAADAABgAAwAAYAAMAAOAAHAADgABwAA4AAcAA+AAP//////wAAA="},
      "3":{w:20,a:30,b:"AfgAf/AcB4MAHCAAwAAGAABgAAYAAGAABgAAwAAcAAOAD/AA/gAAcAABwAAOAABgAAcAADAAAwAAMAADAAAwAAbAAO4AHHwHgf/gA/gAAAA="},
      "4":{w:19,a:30,b:"AA8AA+AA7AAZgAYwAMYAMMAGGAGDADBgDAwDgYBgMBgGAwDAwBgYAwYAYMAMMAGOADH/////+AAYAAMAAGAADAABgAAwAP/AH/gAAA=="},
      "5":{w:20,a:20,b:"P//D//w4AAOAADgAA4AAOAADgAA4AAOAADgAA4/AO/8D4DgYAMAABgAAYAADAAAwAAMAADAAAwAAMAADAABsAAbgAOcAHDwHgP/gAfgAAAA="},
      "A":{w:29,a:32,b:"AAAAAAAAAAP/wAAf/gAAAZgAAAzAAABjAAAGGAAAMMAAAYMAABgYAADAwAAGAwAAYBgAAwDAADADAAGAGAAMAGAAwAMAB//4AD//4AMAAwAYABgAwABgDAADAGAADAYAAGAwAAMBgAAMf8AP//4Af+AAAAA="},
      "B":{w:24,a:30,b:"AAAAAAAA//8A///gGABwGAA4GAAYGAAMGAAMGAAMGAAMGAAMGAAYGAA4GADwH//gH//wGAA4GAAMGAAGGAAHGAADGAADGAADGAADGAADGAAGGAAOGAAc///4///AAAAA"},
      "C":{w:24,a:33,b:"AAAAAAAAAH8GAf/GB4D2DgA+HAAOOAAOMAAGcAAGYAAAYAAA4AAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAYAAAYAAAYAAAMAAAOAADGAAHDAAOBwAcA8B4AP/gAD8A"},
    },
  },
};
